name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Initialize Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

  nodes:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node: [14, 17]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Initialize Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
    
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Initialize Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Initialize Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Test
        run: npm run test:nyc

  coveralls:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Initialize Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Configure Coveralls
        run: 'echo "repo_token: $COVERALLS_REPO_TOKEN" > .coveralls.yml'
        shell: bash
        env:
          COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN}}

      - name: Report Coverage
        run: npm run coverage
